/*
-- Query: SELECT * FROM TP1BD.Pais
LIMIT 0, 1000

-- Date: 2012-09-12 18:48
*/
INSERT INTO `Pais` (`idPais`,`nombre`) VALUES (1,'Argentina');
INSERT INTO `Pais` (`idPais`,`nombre`) VALUES (2,'EEUU');
INSERT INTO `Pais` (`idPais`,`nombre`) VALUES (3,'Puerto Rico');
INSERT INTO `Pais` (`idPais`,`nombre`) VALUES (4,'República Dominicana');
INSERT INTO `Pais` (`idPais`,`nombre`) VALUES (5,'Brasil');
INSERT INTO `Pais` (`idPais`,`nombre`) VALUES (6,'Panamá');
INSERT INTO `Pais` (`idPais`,`nombre`) VALUES (7,'Canadá');
INSERT INTO `Pais` (`idPais`,`nombre`) VALUES (8,'México');

INSERT INTO `Estadio` (`idEstadio`, `descripcion`) VALUES ('1', 'TD Garden, Boston, MA');
INSERT INTO `Estadio` (`idEstadio`, `descripcion`) VALUES ('2', 'United Center, Chicago, IL');
INSERT INTO `Estadio` (`idEstadio`, `descripcion`) VALUES ('3', 'Staples Center, Los Angeles, CA');
INSERT INTO `Estadio` (`idEstadio`, `descripcion`) VALUES ('4', 'Madison Square Garden, New York, NY');
INSERT INTO `Estadio` (`idEstadio`, `descripcion`) VALUES ('5', 'American Airways Center, Orlando, FL');
INSERT INTO `Estadio` (`idEstadio`, `descripcion`) VALUES ('6', 'American Airlines Arena, Miami, FL');
INSERT INTO `Estadio` (`idEstadio`, `descripcion`) VALUES ('7', 'FedEx Center, Memphis, TN');
INSERT INTO `Estadio` (`idEstadio`, `descripcion`) VALUES ('8', 'Bradley Center, Milwaukee, WI');


INSERT INTO `Fase` (`idFase`, `descripcion`) VALUES ('1', 'Fase de Grupos');
INSERT INTO `Fase` (`idFase`, `descripcion`) VALUES ('2', 'Partido por 5to Puesto');
INSERT INTO `Fase` (`idFase`, `descripcion`) VALUES ('3', 'Semifinal');
INSERT INTO `Fase` (`idFase`, `descripcion`) VALUES ('4', 'Partido por 3er puesto');
INSERT INTO `Fase` (`idFase`, `descripcion`) VALUES ('5', 'Final');

INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('1', 'Flavio Pedemonti', '1');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('2', 'Phil Kennedy', '2');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('3', 'Micky Vainilla', '3');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('4', 'Juan Pérez García', '4');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('5', 'Jorge Meconio', '5');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('6', 'Violencia Rivas', '6');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('7', 'Bombita Rodríguez', '7');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('8', 'Roberto Quenedi', '8');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('9', 'Pedro Saborido', '1');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('10', 'Luis Almirante Brown', '1');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('11', 'Joey Crawford', '2');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('12', 'Dick Bavetta', '2');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('13', 'Pomelo', '3');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('14', 'Kosher Waters', '3');
INSERT INTO `Arbitro` (`idArbitro`, `nombre`, `idPais`) VALUES ('15', 'Jorge Peres', '4');

INSERT INTO `Seleccion` (`idSeleccion`, `grupo`, `hospedaje`, `arribo`, `idPais`, `idEstadio`) VALUES ('1', 'A', 'Sheraton Hotel', SYSDATE(), '1', '1');
INSERT INTO `Seleccion` (`idSeleccion`, `grupo`, `hospedaje`, `arribo`, `idPais`, `idEstadio`) VALUES ('2', 'B', 'Hilton Plaza', SYSDATE(), '2', '2');
INSERT INTO `Seleccion` (`idSeleccion`, `grupo`, `hospedaje`, `arribo`, `idPais`, `idEstadio`) VALUES ('3', 'B', 'Ritz Hotel', SYSDATE(), '3', '3');
INSERT INTO `Seleccion` (`idSeleccion`, `grupo`, `hospedaje`, `arribo`, `idPais`, `idEstadio`) VALUES ('4', 'B', 'Plaza Park', SYSDATE(), '4', '4');
INSERT INTO `Seleccion` (`idSeleccion`, `grupo`, `hospedaje`, `arribo`, `idPais`, `idEstadio`) VALUES ('5', 'A', 'Caesar\'s Palace', SYSDATE(), '5', '5');
INSERT INTO `Seleccion` (`idSeleccion`, `grupo`, `hospedaje`, `arribo`, `idPais`, `idEstadio`) VALUES ('6', 'A', 'Luxury Stay', SYSDATE(), '6', '6');
INSERT INTO `Seleccion` (`idSeleccion`, `grupo`, `hospedaje`, `arribo`, `idPais`, `idEstadio`) VALUES ('7', 'B', 'Holiday Inn', SYSDATE(), '7', '7');
INSERT INTO `Seleccion` (`idSeleccion`, `grupo`, `hospedaje`, `arribo`, `idPais`, `idEstadio`) VALUES ('8', 'A', 'Hotel du Nord', SYSDATE(), '8', '8');

INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('1', 'Luis Scola', '31', 'J', '1');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('2', 'Emanuel Ginóbili', '32', 'J', '1');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('3', 'Fabricio Oberto', '35', 'J', '1');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('4', 'Pablo Prigioni', '35', 'J', '1');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('5', 'Andrés Nocioni', '33', 'J', '1');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('6', 'Facundo Campazzo', '23', 'J', '1');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('7', 'Rubén Wolkowyski', '30', 'J', '1');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('8', 'Carlos Delfino', '30', 'J', '1');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('9', 'Juan Gutiérrez', '27', 'J', '1');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('10', 'Leo Gutiérrez', '26', 'J', '1');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('11', 'Juan Ignacio Sánchez', '33', 'J', '1');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('12', 'Hernán Jasen', '29', 'J', '1');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('13', 'Rajon Rondo', '25', 'J', '2');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('14', 'LeBron James', '27', 'J', '2');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('15', 'Dwyane Wade', '30', 'J', '2');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('16', 'Chris Bosh', '28', 'J', '2');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('17', 'Paul Pierce', '32', 'J', '2');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('18', 'Kevin Garnett', '35', 'J', '2');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('19', 'Tim Duncan', '36', 'J', '2');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('20', 'Chris Paul', '27', 'J', '2');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('21', 'Kobe Bryant', '33', 'J', '2');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('22', 'Lamar Odom', '34', 'J', '2');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('23', 'Tyson Chandler', '29', 'J', '2');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('24', 'Blake Griffin', '23', 'J', '2');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('25', 'Leandro Barbosa', '23', 'J', '5');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('26', 'Marcelo Huertas', '32', 'J', '5');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('27', 'Nené Hilário', '24', 'J', '5');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('28', 'Tiago Splitter', '25', 'J', '5');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('29', 'Anderson Varejao', '26', 'J', '5');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('30', 'Guilherme Giovannoni', '27', 'J', '5');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('31', 'Marcelo Machado', '22', 'J', '5');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('32', 'Alex García', '26', 'J', '5');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('33', 'Leandro Araújo', '23', 'J', '5');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('34', 'Raul Togni', '26', 'J', '5');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('35', 'Larry Taylor', '27', 'J', '5');
INSERT INTO `Integrante` (`nroPasaporte`, `nombre`, `edad`, `esUn`, `idSeleccion`) VALUES ('36', 'Caio Torres', '24', 'J', '5');

INSERT INTO `Posicion` (`idPosicion`, `descripcion`) VALUES ('1', 'Base');
INSERT INTO `Posicion` (`idPosicion`, `descripcion`) VALUES ('2', 'Escolta');
INSERT INTO `Posicion` (`idPosicion`, `descripcion`) VALUES ('3', 'Ala');
INSERT INTO `Posicion` (`idPosicion`, `descripcion`) VALUES ('4', 'Ala-Pivot');
INSERT INTO `Posicion` (`idPosicion`, `descripcion`) VALUES ('5', 'Pivot');

INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('1', 'San Antonio Spurs', '4');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('2', 'Boston Celtics', '2');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('3', 'San Antonio Spurs', '5');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('4', 'Los Angeles Clippers', '1');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('5', 'Detroit Pistons', '3');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('6', 'Sacramento Kings', '1');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('7', 'Boston Celtics', '5');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('8', 'San Antonio Spurs', '3');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('9', 'Los Angeles Clippers', '4');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('10', 'Oklahoma City Thunder', '4');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('11', 'San Antonio Spurs', '1');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('12', 'Los Angeles Clippers', '2');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('13', 'Boston Celtics', '1');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('14', 'Detroit Pistons', '3');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('15', 'Los Angeles Clippers', '2');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('16', 'San Antonio Spurs', '4');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('17', 'Boston Celtics', '3');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('18', 'Golden State Warriors', '5');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('19', 'Atlanta Hawks', '4');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('20', 'Los Angeles Clippers', '1');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('21', 'San Antonio Spurs', '2');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('22', 'Boston Celtics', '4');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('23', 'San Antonio Spurs', '5');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('24', 'Sacramento Kings', '4');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('25', 'Los Angeles Clippers', '2');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('26', 'Boston Celtics', '1');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('27', 'San Antonio Spurs', '5');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('28', 'Detroit Pistons', '4');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('29', 'Los Angeles Clippers', '5');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('30', 'Boston Celtics', '4');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('31', 'San Antonio Spurs', '3');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('32', 'Sacramento Kings', '2');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('33', 'Boston Celtics', '1');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('34', 'Boston Celtics', '3');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('35', 'San Antonio Spurs', '2');
INSERT INTO `Jugador` (`nroPasaporte`, `equipo`, `idPosicion`) VALUES ('36', 'Los Angeles Clippers', '1');

INSERT INTO `Partido` (`nroPartido`, `primerCuartoLocal`, `segundoCuartoLocal`, `tercerCuartoLocal`, `cuartoCuartoLocal`, `primerCuartoVisitante`, `segundoCuartoVisitante`, `tercerCuartoVisitante`, `cuartoCuartoVisitante`,`fecha`, `idFase`, `idSeleccionLocal`, `idSeleccionVisitante`, `idEstadio`) VALUES ('1', '15', '23', '21', '17', '19', '14', '27', '24', SYSDATE() - 2,'1', '1', '5', '1');
INSERT INTO `Partido` (`nroPartido`, `primerCuartoLocal`, `segundoCuartoLocal`, `tercerCuartoLocal`, `cuartoCuartoLocal`, `primerCuartoVisitante`, `segundoCuartoVisitante`, `tercerCuartoVisitante`, `cuartoCuartoVisitante`,`fecha`, `idFase`, `idSeleccionLocal`, `idSeleccionVisitante`, `idEstadio`) VALUES ('2', '19', '10', '17', '30', '18', '26', '26', '23',SYSDATE() - 1, '1', '2', '1', '2');
INSERT INTO `Partido` (`nroPartido`, `primerCuartoLocal`, `segundoCuartoLocal`, `tercerCuartoLocal`, `cuartoCuartoLocal`, `primerCuartoVisitante`, `segundoCuartoVisitante`, `tercerCuartoVisitante`, `cuartoCuartoVisitante`,`fecha`, `idFase`, `idSeleccionLocal`, `idSeleccionVisitante`, `idEstadio`) VALUES ('3', '22', '27', '18', '31', '12', '20', '26', '28', SYSDATE(), '1','5', '2', '3');
INSERT INTO `Partido` (`nroPartido`, `primerCuartoLocal`, `segundoCuartoLocal`, `tercerCuartoLocal`, `cuartoCuartoLocal`, `primerCuartoVisitante`, `segundoCuartoVisitante`, `tercerCuartoVisitante`, `cuartoCuartoVisitante`,`fecha`, `idFase`, `idSeleccionLocal`, `idSeleccionVisitante`, `idEstadio`) VALUES ('4', '16', '25', '26', '24', '18', '24', '27', '27',SYSDATE(), '5', '1', '2', '4');

INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('1', '1', '1', '1');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('2', '1', '2', '1');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('3', '1', '3', '1');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('4', '1', '4', '1');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('5', '1', '5', '1');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('6', '0', '6', '1');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('7', '1', '25', '1');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('8', '1', '26', '1');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('9', '1', '27', '1');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('10', '1', '28', '1');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('11', '1', '29', '1');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('12', '0', '30', '1');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('13', '1', '13', '2');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('14', '1', '14', '2');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('15', '1', '15', '2');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('16', '1', '16', '2');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('17', '1', '17', '2');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('18', '0', '18', '2');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('19', '1', '6', '2');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('20', '1', '7', '2');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('21', '1', '8', '2');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('22', '1', '9', '2');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('23', '1', '10', '2');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('24', '0', '11', '2');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('25', '1', '31', '3');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('26', '1', '32', '3');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('27', '1', '33', '3');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('28', '1', '34', '3');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('29', '1', '35', '3');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('30', '0', '36', '3');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('31', '1', '13', '3');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('32', '1', '14', '3');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('33', '1', '15', '3');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('34', '1', '16', '3');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('35', '1', '17', '3');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('36', '0', '18', '3');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('37', '1', '11', '4');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('38', '1', '12', '4');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('39', '1', '1', '4');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('40', '1', '2', '4');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('41', '1', '3', '4');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('42', '0', '4', '4');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('43', '1', '13', '4');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('44', '1', '14', '4');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('45', '1', '15', '4');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('46', '1', '16', '4');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('47', '1', '17', '4');
INSERT INTO `Participacion` (`idParticipacion`, `esTitular`, `nroPasaporte`, `nroPartido`) VALUES ('48', '0', '18', '4');

INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (4,1,1,27,13,5);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (1,2,2,33,17,4);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (0,3,3,34,19,2);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (5,4,4,38,15,15);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (9,5,5,31,4,3);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (4,6,6,37,10,12);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (1,7,7,33,13,9);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (8,8,8,38,11,8);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (3,9,9,31,17,6);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (6,10,10,37,13,12);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (1,11,11,34,30,1);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (0,12,12,27,10,0);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (16,13,13,33,12,12);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (4,14,14,34,14,6);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (2,15,15,38,17,3);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (4,16,16,31,16,16);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (8,17,17,27,20,1);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (1,18,18,37,7,4);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (5,19,19,31,19,15);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (6,20,20,37,13,0);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (0,21,21,33,17,4);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (2,22,22,34,22,5);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (4,23,23,38,15,13);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (5,24,24,27,6,1);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (3,25,25,33,12,2);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (1,26,26,37,19,1);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (4,27,27,38,7,2);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (12,28,28,27,31,9);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (1,29,29,34,16,8);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (7,30,30,31,13,20);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (4,31,31,31,14,1);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (9,32,32,37,13,6);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (4,33,33,38,2,7);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (6,34,34,27,28,12);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (2,35,35,34,13,13);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (18,36,36,33,16,4);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (1,37,37,38,4,12);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (0,38,38,33,8,8);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (2,39,39,34,13,7);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (3,40,40,37,20,6);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (6,41,41,27,6,4);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (13,42,42,31,40,5);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (2,43,43,31,12,7);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (4,44,44,38,16,4);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (2,45,45,34,10,9);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (0,46,46,27,18,16);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (1,47,47,33,10,5);
INSERT INTO `estadistica` (`asistencias`,`idEstadistica`,`idParticipacion`,`minutos`,`puntos`,`rebotes`) VALUES (3,48,48,37,30,10);
